Add ConnectionFactory and Apps for data manipulation
andradeoromulo/cicerone pull request #5
Opened 2021-07-14 15:01 UTC by andradeoromulo

Proposta de resolução dos desafios da Semana 4 do Level Up.

2021-07-14 22:14 UTC, alexandreaquiles requested changes
Olá, @andradeoromulo 

Está ótimo, direto ao ponto!

Mas eu esperava que fosse criada uma DAO.

Deixei um pequeno desafio na `ConnectionFactory`. Gostei do seu Singleton!

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/scripts/queries.sql
> +-- All enabled categories by order
Creio que esse tipo de arquivo que não é `.java` deveria ficar no `src/main/resources`.

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/apps/DeletionApp.java
> +            connection.setAutoCommit(false);
O ideal era que esse código que trabalha com tudo do pacote `java.sql.*` ficasse escondido em um objeto específico: uma DAO.

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/apps/InsertionApp.java
> +            connection.setAutoCommit(false);
O ideal era esconder código JDBC em uma DAO.
Essa DAO receberia um objeto `Course` e poderia até setar o novo id no objeto.

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/apps/ReportApp.java
> +            connection.setAutoCommit(false);
Esconder JDBC numa DAO.

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/apps/UpdateApp.java
> +            connection.setAutoCommit(false);
JDBC na DAO.

2021-07-14 22:14 UTC, alexandreaquiles commented on src/main/java/com/cicerone/db/factory/ConnectionFactory.java
> +        pool.setMaxPoolSize(10);
Está ótimo!

Um desafio: como permitir que a URL, o usuário, a senha e o tamanho do pool de conexões sejam sobrescritos com variáveis de ambiente?

Assim, poderíamos modificar os valores sem recompilar a aplicação!

2021-07-16 01:42 UTC, andradeoromulo commented on src/main/java/com/cicerone/db/scripts/queries.sql
> +-- All enabled categories by order
Feito :)

2021-07-16 01:44 UTC, andradeoromulo commented on src/main/java/com/cicerone/db/factory/ConnectionFactory.java
> +        pool.setMaxPoolSize(10);
Não sei se consegui alcançar o que você pensou, mas coloquei toda a configuração do c3p0 em um arquivo XML. Deu trabalho pra descobrir como fazer isso 😂

2021-07-16 01:47 UTC, andradeoromulo commented on src/main/java/com/cicerone/db/apps/DeletionApp.java
> +            connection.setAutoCommit(false);
Coloquei toda a manipulação de dados em classes DAO. Eu fiquei em dúvida entre enviar a `Connection` para a DAO ou criá-la lá dentro. Mesmo com a desvantagem de não conseguir controlar a transação pelo lado de fora ou ter a atomicidade em todo o processo quando uma DAO chama a outra, achei melhor criar a conexão dentro da DAO e isolar completamente a manipulação SQL dentro dela. Além disso, cada método pede a sua própria conexão em vez de ter uma sempre disponível para a classe. Achei melhor assim para poder liberar a conexão de volta pro pool.

2021-07-16 18:57 UTC, alexandreaquiles approved these changes

2021-07-16 18:57 UTC, merged